steps:
  # Note: $PROJECT_ID is automatically substituted by Cloud Build based on the project running the build.
  # Build Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/expense-tracking-repo/expense-tracking-backend', './backend']

  # Build Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/expense-tracking-repo/expense-tracking-frontend', './frontend']

  # Push Images
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/expense-tracking-repo/expense-tracking-backend']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/expense-tracking-repo/expense-tracking-frontend']

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/expense-tracking-repo/expense-tracking-backend'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/expense-tracking-repo/expense-tracking-frontend'
